groups:
  - name: infrastructure-alerts
    rules:

      # 1️⃣ Instance down
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance down"
          description: "Prometheus cannot scrape {{ $labels.instance }}"

      # 2️⃣ CPU usage high
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 85% on {{ $labels.instance }}"

      # 3️⃣ Disk almost full
      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"})
              / node_filesystem_size_bytes{fstype!="tmpfs"} * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage"
          description: "Disk usage is above 90% on {{ $labels.instance }}"

      # 4️⃣ Website unreachable (Blackbox)
      - alert: WebsiteDown
        expr: probe_success == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Website is down"
          description: "Blackbox probe failed for {{ $labels.instance }}"