name: Test AWS Connection

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug OIDC token
        run: |
          echo "Requesting OIDC token..."
          curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
            | jq -r '.value' | cut -d "." -f2 | base64 -d

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::682135518833:role/Docmost-GitHub-Role
          aws-region: eu-west-3

      - name: Test AWS identity
        run: aws sts get-caller-identity
