name: Terraform Infrastructure

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "infra/**"
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # obligatoire pour OIDC
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ github.ref == 'refs/heads/main' && 'arn:aws:iam::682135518833:role/Docmost-GitHub-Role' || 'arn:aws:iam::682135518833:role/Docmost-GitHub-Dev-Role' }}
          aws-region: eu-west-3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=infra init

      - name: Terraform Plan Dev
        if: github.ref == 'refs/heads/dev'
        run: terraform -chdir=infra plan -var="allowed_ssh_ip=${{ secrets.ALLOWED_SSH_IP_DEV }}"

      - name: Terraform Plan Prod
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=infra plan -var="allowed_ssh_ip=${{ secrets.ALLOWED_SSH_IP_PROD }}"

      - name: Terraform Apply Dev
        if: github.ref == 'refs/heads/dev'
        run: terraform -chdir=infra apply -auto-approve -var="allowed_ssh_ip=${{ secrets.ALLOWED_SSH_IP_DEV }}"

      - name: Terraform Apply Prod
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=infra apply -auto-approve -var="allowed_ssh_ip=${{ secrets.ALLOWED_SSH_IP_PROD }}"