name: Terraform Infrastructure

on:
  push:
    paths:
      - 'infra/**'
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    permissions:
      id-token: write      # OIDC obligatoire
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ github.ref == 'refs/heads/main' && 'arn:aws:iam::682135518833:role/Docmost-GitHub-Role' || 'arn:aws:iam::682135518833:role/Docmost-GitHub-Dev-Role' }}
          aws-region: eu-west-3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=infra init

      - name: Terraform Plan
        run: terraform -chdir=infra plan

      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve